#Koundinya M
#17PE10024
#Petroleum Engineering
#Assignement-1

CREATE DATABASE DB2;
USE DB2;

/*			STUDENT TABLE*/
CREATE TABLE STUDENT_DATA(
STU_ID VARCHAR(9) NOT NULL PRIMARY KEY,
STU_NAME VARCHAR(15),
STU_BRANCH CHAR(2),
CGPA FLOAT
);

INSERT INTO STUDENT_DATA VALUES ('17PE1001','PRADYUMNA','PE',9.2);
INSERT INTO STUDENT_DATA VALUES ('17PE1003','RAHUL JAIN','PE',8.51);
INSERT INTO STUDENT_DATA VALUES ('17CH1004','SHASHI KUMAR','CH',9.24);
INSERT INTO STUDENT_DATA VALUES ('17PE1005','MARUTHI RAO ','PE',6.2);
INSERT INTO STUDENT_DATA VALUES ('17CH1006','MANASA M','CH',8.41);
INSERT INTO STUDENT_DATA VALUES ('17PE1007','JOSEPH','PE',8.92);
INSERT INTO STUDENT_DATA VALUES ('17CH1008','SHEKAR RAO','CH',7.12);
INSERT INTO STUDENT_DATA VALUES ('17CH1009','VENKAT RAO','CH',7.29);
INSERT INTO STUDENT_DATA VALUES ('17CH1011','SAI BABU','CH',4.21);
INSERT INTO STUDENT_DATA VALUES ('17PE1031','SUNIL KUMAR','PE',8.76);

/*			COMPANY_PROFILE*/
CREATE TABLE COMPANY_PROFILE(
C_ID INT NOT NULL,
C_NAME VARCHAR(20),
CUTOFF FLOAT,
INITIAL_PACKAGE INT,
BRANCH CHAR(2)
);

INSERT INTO COMPANY_PROFILE VALUES (1,'HPCL',7.0,1500000,'CH');
INSERT INTO COMPANY_PROFILE VALUES (2,'ONGC',7.5,1120000,'PE');
INSERT INTO COMPANY_PROFILE VALUES (3,'GAIL',7.3,1760000,'CH');
INSERT INTO COMPANY_PROFILE VALUES (4,'AMARON',7.0,1410000,'PE');
INSERT INTO COMPANY_PROFILE VALUES (5,'RELIANCE',8.1,1910000,'PE');
INSERT INTO COMPANY_PROFILE VALUES (6,'OIL INDIA',8.5,12300000,'PE');

/*			PLACED STUDENTS*/
CREATE TABLE PLACED_STUDENTS(
STU_ID CHAR(10) NOT NULL,
STU_NAME VARCHAR (15) NOT NULL,
STU_BRANCH CHAR(2),
C_NAME VARCHAR(20),
INITIAL_PACKAGE INT
);

INSERT INTO PLACED_STUDENTS VALUES ('17PE1007','JOSEPH','PE','HPCL',1500000);
INSERT INTO PLACED_STUDENTS VALUES ('17PE1031','SUNIL KUMAR','PE','HPCL',1500000);
INSERT INTO PLACED_STUDENTS VALUES ('17CH1011','SAI BABU','CH','HPCL',1500000);
INSERT INTO PLACED_STUDENTS VALUES ('17PE1005','MARUTHI RAO ','PE','GAIL',1760000);
INSERT INTO PLACED_STUDENTS VALUES ('17CH1006','MANASA M','CH','AMARON',1410000);
INSERT INTO PLACED_STUDENTS VALUES ('17CH1009','VENKAT RAO','CH','RELIANCE',1910000);

SELECT * FROM STUDENT_DATA;
SELECT * FROM COMPANY_PROFILE;
SELECT * FROM PLACED_STUDENTS; 



/*						REPORT						*/
/*			NUMBER OF STUDENTS PLACED			*/
SELECT PLACED_STUDENTS.STU_ID,PLACED_STUDENTS.STU_NAME,PLACED_STUDENTS.STU_BRANCH,C_NAME FROM PLACED_STUDENTS INNER JOIN STUDENT_DATA ON PLACED_STUDENTS.STU_NAME=STUDENT_DATA.STU_NAME; 

/*			TOP 3 RECRUITERS			*/
SELECT C_NAME,COUNT(C_NAME) FROM PLACED_STUDENTS GROUP BY C_NAME;

/*			BEST,AVERAGE,LOWEST PACKAGE OFFERED			*/
SELECT MAX(INITIAL_PACKAGE),AVG(INITIAL_PACKAGE),MIN(INITIAL_PACKAGE) FROM COMPANY_PROFILE;

/*			SHORT LISTING CANDIDATES FOR INTERVIEWS BASED ON COMPANY CUTOFF			*/
SELECT STU_NAME,CGPA,C_NAME,CUTOFF FROM STUDENT_DATA INNER JOIN COMPANY_PROFILE ON STUDENT_DATA.CGPA>COMPANY_PROFILE.CUTOFF; 

/*			SHORT LISTING CANDIDATES FOR INTERVIEWS BASED ON BRANCH (PE OR CH)			*/
SELECT STU_NAME,STU_BRANCH,CGPA,C_NAME,CUTOFF FROM STUDENT_DATA INNER JOIN COMPANY_PROFILE ON STUDENT_DATA.CGPA>COMPANY_PROFILE.CUTOFF; 

/*			COMMAND FOR STUDENTS WHO HAVE NOT MORE THAN 2 JOBS			*/
SELECT STU_NAME,C_NAME FROM PLACED_STUDENTS GROUP BY C_NAME HAVING COUNT(STU_NAME)<3;
